### PR TITLE
TOMEE-3826 Exclusion list implemented in Transformation to preserve jar signature

### PR DESCRIPTION
**Pull request by cesarhernandezgt**

### CODE REVIEW

**Review by rzo1 — APPROVED** [review]

**Comment by jeanouii** [comment]
Hi Cesar,

A couple of comments here

- we should always skip signed jars. Patching those will always fail (goal of the signature). We can have a force patch signed jars flag for testing purpose, but it should be off by default

- the skip jars feature is a good one. Even though we have a predefined list of jars we know we can exclude, it would be great to allow the user to redefine it so we avoid further updates to the plugin and releases.


Do you mind giving it a try?
Otherwise, we can merge this one and I can give it a try after

**Comment by jeanouii** [comment]
I remember we had that kind of issue with EclipseLink when working on TCK

We added a feature to replace a jar with a default version which in essence is similar to skip.

https://github.com/apache/tomee-patch-plugin/blob/master/tomee-patch-core/src/main/java/org/apache/tomee/patch/core/Transformation.java#L90

You can also read <replace> in the readme
https://github.com/apache/tomee-patch-plugin

**Comment by cesarhernandezgt** [comment]
Thank you @rzo1 and @jeanouii for the review.

Replying inline the feedback:

> we should always skip signed jars. 

I think the list of jars that are signed should be agnostic to the plugin. Also managing the version for each jar would make this hard to maintain since signed the jars are actually the ones defined in the apache/tomee project and not the jars from the apache/tomee-patch-plugin. 


> I remember we had that kind of issue with EclipseLink when working on TCK

Thank you for the pointer, this helped me to improve the solution I come up with in commit b79126f and allow the end-user to define the list of jars to skip as part of the maven plugin configuration section.

This means that the end-user of the plugin (tomee source code for example) can define the jar and versions to skip when transformer and artifact as demonstrated in https://github.com/apache/tomee-patch-plugin/pull/5/commits/b79126ff8993bb0703b757aa2939d3b8d33f085c#diff-1194561cbea346acb1bea37d81fdf5c70def982dcbb0c64eca2a96bc51941124R125-R137

I tried this and it worked for both profiles in TomEE build code: https://github.com/apache/tomee/blob/f7b57d811081c5a729664e92ee28cd2fff8672f9/tomee/apache-tomee/pom.xml#L549-L556

What do you think?

**Review by rzo1 — APPROVED** [review]

**Review by jeanouii — APPROVED** [review]
Looks good to me

**Comment by jeanouii** [comment]
@cesarhernandezgt Can you create an issue in Github or in Apache JIRA assigned to this component so we can track

**Pull request merged**
